"""Turn raw transactions into stable client entities.

IEEE-CIS deliberately ships no user id. Every transaction is anonymous. But the
labels were generated by propagating a reported chargeback to later
transactions sharing a user account, email or billing address -- so a client
notion demonstrably exists in the data, and recovering it is the single highest
-value feature-engineering step available.

The reconstruction below is the community-standard one, with the reasoning
spelled out because it is not obvious.
"""
from __future__ import annotations

import pandas as pd

from ringfence import config


def add_card_anchor(df: pd.DataFrame) -> pd.DataFrame:
    """Derive the day a card first appeared: a stable per-card constant.

    D1 is documented as "days since the card began transacting". So for any
    transaction, (day_of_transaction - D1) is the card's *start day*, which is
    the same value for every transaction made by that card. Two rows with the
    same card fingerprint AND the same start day are almost certainly the same
    physical card; two rows with the same fingerprint but different start days
    are different cards that happen to collide on the coarse fingerprint.

    This is what upgrades a lossy fingerprint into a usable client key.
    """
    df = df.copy()
    day = df[config.TIME_COL] // 86400
    df["_card_anchor"] = (day - df["D1"]).astype("float32")
    return df


def build_client_id(df: pd.DataFrame) -> pd.Series:
    """Concatenate the fingerprint columns plus the anchor into one string key."""
    parts = []
    for col in config.CLIENT_KEYS:
        if col not in df.columns:
            continue
        parts.append(df[col].astype("string").fillna("na"))
    parts.append(df["_card_anchor"].astype("string").fillna("na"))
    client = parts[0]
    for p in parts[1:]:
        client = client.str.cat(p, sep="|")
    return client.rename("client_id")


def resolve(df: pd.DataFrame) -> pd.DataFrame:
    """Attach `client_id` to every row."""
    df = add_card_anchor(df)
    df["client_id"] = build_client_id(df)
    return df
